Import AbstractBaseUser from base_user to avoid INSTALLED_APPS exception
Starting in Django 1.9, Django became much more strict about listing
imported apps in `INSTALLED_APPS`. The `django.contrib.auth.models`
module requires the `django.contrib.auth` app for the more complex
Classes within, even though `AbstractBaseUser` doesn't use them.

As such, to avoid having to add to modify `INSTALLED_APPS` when only
using `AbstractBaseUser`, that class has now been moved to a separate
module, so it can be imported standalone. See:
https://code.djangoproject.com/ticket/24564
https://github.com/django/django/pull/4438

This fixes the following exception when using hawkrest under Django 1.9:

RuntimeError: Model class django.contrib.contenttypes.models.ContentType
doesn't declare an explicit app_label and isn't in an application in
INSTALLED_APPS.