Give HawkAuthenticatedUser a save() method to match AbstractBaseUser
A `save()` method was added to `AbstractBaseUser` in:
https://code.djangoproject.com/ticket/25052
https://github.com/django/django/pull/4955

This fixes test failures under Django 1.9 of the form:

FAIL: tests/test_authentication.py:TestHawkAuthenticatedUser.test_method_compliance
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/Ed/src/hawkrest/tests/test_authentication.py", line 208, in test_method_compliance
    .format(name))
AssertionError: HawkAuthenticatedUser is missing method: save